{:fenc :utf-8
 :backup false
 :swapfile false
 :autoread true
 :tabstop 4
 :shiftwidth 4
 :expandtab true
 :number true
 :scrolloff 10
 :cursorline true
 :incsearch true
 :termguicolors true
 :background :dark
 :mouse :a
 :t_8f "^[[38;2;%lu;%lu;%lum"
 :t_8b "^[[48;2;%lu;%lu;%lum"
 :list true
 :listchars "tab:»-,trail:□"
 :spell true
 :startofline true
 :spelllang "en,cjk"
 :guifont "HackGen Console"}
